# Use localhost for testing
group_localhost:
  hosts:
    localhost:
      ansible_connection: "local"
      ansible_python_interpreter: "/usr/bin/python3"
  vars:
    system_name: "local"
    group: "csc"
    appl_dir: "{{ ansible_env.HOME }}/scratch/appl/soft/math"
    modulefiles_dir: "{{ ansible_env.HOME}}/scratch/appl/modulefiles"
    julia_gpu_type: "cuda"
group_puhti:
  hosts:
    puhti-login13.csc.fi:
      ansible_connection: "ssh"
      ansible_python_interpreter: "/usr/bin/python3.9"
      ansible_remote_tmp: "/local_scratch/$USER/.ansible/tmp"
  vars:
    system_name: "puhti"
    group: "p_installation"
    appl_dir: "/appl/soft/math"
    modulefiles_dir: "/appl/modulefiles"
    julia_gpu_type: "cuda"
group_mahti:
  hosts:
    mahti-login13.csc.fi:
      ansible_connection: "ssh"
      ansible_python_interpreter: "/usr/bin/python3.9"
      ansible_remote_tmp: "/local_scratch/$USER/.ansible/tmp"
  vars:
    system_name: "mahti"
    group: "m_installation"
    appl_dir: "/appl/soft/math"
    modulefiles_dir: "/appl/modulefiles"
    julia_gpu_type: "cuda"
group_lumi:
  hosts:
    lumi-uan04.csc.fi:
      ansible_connection: "ssh"
      ansible_python_interpreter: "/opt/cray/pe/python/3.9.13.1/bin/python3.9"
  vars:
    system_name: "lumi"
    group: "appl_csc"
    appl_dir: "/appl/local/csc/soft/math"
    modulefiles_dir: "/appl/local/csc/modulefiles"
    julia_gpu_type: "amdgpu"
