- name: "Install julia-jupyter environment"
  hosts:
    - "group_puhti"
    - "group_mahti"
    - "group_lumi"
  become: false

  tasks:
    - name: "Include variables"
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/version/{{ version }}.yaml"

    - name: "Create julia-jupyter application directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia-jupyter"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Create julia-jupyter application directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia-jupyter/{{ version }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Create Python virtual environment"
      ansible.builtin.command: |
        python3.9 -m venv "{{ version }}"
      args:
        chdir: "{{ appl_dir }}/julia-jupyter"
        creates: "{{ appl_dir }}/julia-jupyter/{{ version }}/bin"

    - name: "Upgrade pip to latest version. We pin the version manually for reproducibility."
      ansible.builtin.command: |
        ./{{ version }}/bin/pip install --upgrade pip==24.3.1
      args:
        chdir: "{{ appl_dir }}/julia-jupyter"

    - name: "Install packages to the virtual environment"
      ansible.builtin.command: |
        ./{{ version }}/bin/pip install {{ requirements }}
      args:
        chdir: "{{ appl_dir }}/julia-jupyter"
        creates: "{{ appl_dir }}/julia-jupyter/{{ version }}/bin/jupyter"

    - name: "Remove the default kernel"
      ansible.builtin.command: |
        ./{{ version }}/bin/jupyter kernelspec remove -y python3
      args:
        chdir: "{{ appl_dir }}/julia-jupyter"
        removes: "{{ appl_dir }}/julia-jupyter/{{ version }}/share/jupyter/kernels/python3"

    - name: "Create julia-jupyter modulefiles directory"
      ansible.builtin.file:
        path: "{{ modulefiles_dir }}/julia-jupyter"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Create a julia-jupyter module"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/julia-jupyter.lua.j2"
        dest: "{{ modulefiles_dir }}/julia-jupyter/{{ version }}.lua"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: "Create julia-jupyter binary directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia-jupyter/bin"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Create script for installing IJulia.jl and kernel"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/templates/install_ijulia_kernel.jl"
        dest: "{{ appl_dir }}/julia-jupyter/bin/install_ijulia_kernel.jl"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
