- name: "Create shared depot directory"
  hosts:
    - "group_localhost"
    - "group_puhti"
    - "group_mahti"
    - "group_lumi"
  become: false

  tasks:
    - name: "Create julia depot directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia-depot"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Create a hidden module for installing shared packages"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/julia-depot.lua.j2"
        dest: "{{ modulefiles_dir }}/.julia-depot.lua"
        mode: "ug=rw,o="
        group: "{{ group }}"

    - name: "Ensure correct access rights"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia-depot"
        state: "directory"
        recurse: true
        mode: "ug=rwX,o=rX"
        group: "{{ group }}"
