- name: "Synchronize lustre partitions on lumi"
  hosts:
    - "group_lumi"
  become: false

  task:
    # TODO: chmod u=rwX,go=rX
    # TODO: sync julia, julia-depot, julia-jupyter, modulefiles/julia, modulefiles/julia-amdgpu, modulefiles/julia-jupyter

    - name: ""
      ansible.builtin.command: |
        rsync --archive --delete "/pfs/lustrep1/{{ appl_dir }}/julia" "{{ item }}/{{ appl_dir }}/julia"
      loop:
        - "/pfs/lustrep2"
        - "/pfs/lustrep3"
        - "/pfs/lustrep4"
