- name: ""
  hosts:
    - "group_localhost"
    - "group_lumi"
  become: false

  tasks:
    - name: ""
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia-test/amdgpu"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: ""
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/runtests.jl"
        dest: "{{ appl_dir }}/julia-test/amdgpu/runtests.jl"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: ""
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/batch.sh"
        dest: "{{ appl_dir }}/julia-test/amdgpu/batch.sh"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: ""
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ system_name }}.sh"
        dest: "{{ appl_dir }}/julia-test/amdgpu/runtests.sh"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
