localhost:
  hosts:
    localhost:
      ansible_connection: "local"
puhti:
  hosts:
    puhti-install:
      ansible_connection: "ssh"
    vars:
      group: "p_installation"
      appl_dir: "/appl/soft/math"
      modulefiles_dir: "/appl/modulefiles"
      modules:
        - "gcc/11"
        - "openmpi/4"
      gpu: "cuda"
mahti:
  hosts:
    mahti-install:
      ansible_connection: "ssh"
    vars:
      group: "m_installation"
      appl_dir: "/appl/soft/math"
      modulefiles_dir: "/appl/modulefiles"
      modules:
        - "gcc/11"
        - "openmpi/4"
      gpu: "cuda"
lumi:
  hosts:
    lumi:
      ansible_connection: "ssh"
    vars:
      group: "appl_csc"
      appl_dir: "/appl/local/csc/soft/math"
      modulefiles_dir: "/appl/local/csc/modulefiles"
      modules:
        - "prgEnv-cray"
      gpu: "amdgpu"
