# Use localhost for testing
group_localhost:
  hosts:
    localhost:
      ansible_connection: "local"
  vars:
    group: "csc"
    appl_dir: "{{ ansible_env.HOME }}/scratch/appl/soft/math"
    modulefiles_dir: "{{ ansible_env.HOME}}/scratch/appl/modulefiles"
    modules:
      - "gcc/11"
      - "openmpi/4"
    julia_gpu: "cuda"
group_puhti:
  hosts:
    puhti-install:
      ansible_connection: "ssh"
      ansible_python_interpreter: "/usr/bin/python3.9"
  vars:
    group: "p_installation"
    appl_dir: "/appl/soft/math"
    modulefiles_dir: "/appl/modulefiles"
    modules:
      - "gcc/11"
      - "openmpi/4"
    julia_gpu: "cuda"
group_mahti:
  hosts:
    mahti-install:
      ansible_connection: "ssh"
      ansible_python_interpreter: "/usr/bin/python3.9"
  vars:
    group: "m_installation"
    appl_dir: "/appl/soft/math"
    modulefiles_dir: "/appl/modulefiles"
    modules:
      - "gcc/11"
      - "openmpi/4"
    julia_gpu: "cuda"
group_lumi:
  hosts:
    lumi-install:
      ansible_connection: "ssh"
      ansible_python_interpreter: "/opt/cray/pe/python/3.9.13.1/bin/python3.9"
  vars:
    group: "appl_csc"
    appl_dir: "/appl/local/csc/soft/math"
    modulefiles_dir: "/appl/local/csc/modulefiles"
    modules:
      - "prgEnv-cray"
    julia_gpu: "amdgpu"
