- name: "Install julia-jupyter environment"
  become: false
  vars:
    repo_dir: "{{ playbook_dir }}/.."

  tasks:
    - name: "Create julia-jupyter application directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia-jupyter"
        state: "directory"

    - name: "Copy requirements for the virtual environment"
      ansible.builtin.copy:
        src: "{{ repo_dir }}/jupyter/requirements-freeze.txt"
        dest: "{{ appl_dir }}/julia-jupyter/requirements.txt"

    - name: "Create Python virtual environment"
      ansible.builtin.command: |
          python3.9 -m venv "env"
      args:
        creates: "{{ appl_dir }}/julia-jupyter/env"
        chdir: "{{ appl_dir }}/julia-jupyter"

    - name: "Install packages to the virtual environment"
      ansible.builtin.command: |
        ./env/bin/pip install requirements.txt
      args:
        creates: "{{ appl_dir }}/julia-jupyter/env/bin/jupyter"
        chdir: "{{ appl_dir }}/julia-jupyter"

    - name: "Remove the default kernel"
      ansible.builtin.command: |
        ./env/bin/jupyter kernelspec remove -y python3
      args:
        removes: "{{ appl_dir }}/julia-jupyter/env/kernels/..."  # TODO
        chdir: "{{ appl_dir }}/julia-jupyter"
