- name: "Install julia environment"
  hosts:
    - "group_localhost"
    - "group_puhti"
    - "group_mahti"
    - "group_lumi"
  become: false
  vars:
    julia_wrapper: "/tmp/julia"

  tasks:
    - name: "Install julia executable wrapper script"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/wrapper/julia.j2"
        dest: "{{ julia_wrapper }}"
        mode: "u=rwx,go="

    - name: "Install MPI.jl"
      ansible.builtin.script:
        cmd: "{{ playbook_dir }}/pkg/mpi.jl"
        executable: "{{ julia_wrapper }}"

    - name: "Install GPU"
      ansible.builtin.script:
        cmd: "{{ playbook_dir }}/pkg/{{ gpu }}.jl"
        executable: "{{ julia_wrapper }}"
