- name: "Install julia environment"
  hosts:
    - "group_localhost"
    - "group_puhti"
    - "group_mahti"
    - "group_lumi"
  become: false
  environment:
    JULIA_PKG_PRECOMPILE_AUTO: "0"
  vars:
    julia_version: "1.9.2"
    julia_wrapper: "/tmp/julia"

  tasks:
    - name: "Install julia wrapper"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/wrapper/julia.j2"
        dest: "{{ julia_wrapper }}"
        mode: "u=rx,go="

    - name: "Install MPI.jl"
      ansible.builtin.script:
        cmd: "{{ playbook_dir }}/pkg/mpi.jl"
        executable: "{{ julia_wrapper }}"

    - name: "Install GPU"
      ansible.builtin.script:
        cmd: "{{ playbook_dir }}/pkg/{{ gpu }}.jl"
        executable: "{{ julia_wrapper }}"

    - name: "Remove julia wrapper"
      ansible.builtin.file:
        path: "{{ julia_wrapper }}"
        state: "absent"
