- name: "Install julia environment"
  hosts:
    - "group_localhost"
    #- "group_puhti"
    #- "group_mahti"
    #- "group_lumi"
  become: false

  tasks:
    - name: "Create julia application directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia"
        state: "directory"
        group: "{{ group }}"

    - name: "Download julia"
      ansible.builtin.get_url:
        url: "{{ julia_url }}"
        dest: "{{ appl_dir }}/julia/{{ julia_version }}.tar.gz"
        checksum: "{{ julia_checksum }}"
        group: "{{ group }}"

    - name: "Extract the julia archive"
      ansible.builtin.unarchive:
        src: "{{ appl_dir }}/julia/{{ julia_version }}.tar.gz"
        dest: "{{ appl_dir }}/julia"
        remote_src: true
        group: "{{ group }}"
        creates: "{{ appl_dir }}/julia/{{ julia_version }}"
        extra_opts:
          - "--transform"
          - "s/julia-{{ julia_version }}/{{ julia_version }}/g"

    - name: "Create julia depot directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia/depot"
        state: "directory"
        group: "{{ group }}"

    - name: "Create julia modulefiles directory"
      ansible.builtin.file:
        path: "{{ modulefiles_dir }}/julia"
        state: "directory"
        group: "{{ group }}"

    - name: "Create julia modulefile"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/modulefiles/julia.lua.j2"
        dest: "{{ modulefiles_dir }}/julia/{{ julia_version }}.lua"
        group: "{{ group }}"

    - name: "Create julia-{{ gpu }} modulefiles directory"
      ansible.builtin.file:
        path: "{{ modulefiles_dir }}/julia-{{gpu}}"
        state: "directory"
        group: "{{ group }}"

    - name: "Create julia-{{ gpu }} modulefile"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/modulefiles/julia-{{ gpu }}.lua"
        dest: "{{ modulefiles_dir }}/julia-{{ gpu }}/{{ julia_version }}.lua"
        group: "{{ group }}"

    #- name: "Create julia-pkg modulefile"
    #  ansible.builtin.copy:
    #    src: "{{ playbook_dir }}/modulefiles/julia-pkg.lua"
    #    dest: "{{ modulefiles_dir }}/.julia-pkg.lua"
    #    mode: "ug=rw,o="
    #    group: "{{ group }}"
