- name: "Install CUDA.jl preferences"
  hosts:
    - "puhti"
    - "mahti"
  become: false

  tasks:
    - name: "Create a directory for the preferences"
      ansible.builtin.file:
        path: "{{ appl_dir }}/julia-cuda/{{ version }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Copy the preferences"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/version/{{ version }}/{{ system_name }}/Project.toml"
        dest: "{{ appl_dir }}/julia-cuda/{{ version }}/Project.toml"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: "Create a directory for the modulefiles"
      ansible.builtin.file:
        path: "{{ modulefiles_dir }}/julia-cuda"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Create a module"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/version/{{ version }}/{{ system_name }}/julia-cuda.lua.j2"
        dest: "{{ modulefiles_dir }}/julia-cuda/{{ version }}.lua"
        mode: "ug=rw,o=r"
        group: "{{ group }}"
