- name: "Install julia environment"
  hosts:
    - "group_localhost"
    - "group_puhti"
    - "group_mahti"
    #- "group_lumi"
  become: false

  tasks:
    - name: "Create a directory for tests"
      ansible.builtin.file:
        path: "{{ appl_dir }}/{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "julia-test"
        - "julia-test/julia"
        - "julia-test/environment"

    - name: ""
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/environment/runtests.jl"
        dest: "{{ appl_dir }}/julia-test/environment/runtests.jl"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: ""
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/environment/{{ system_name }}.sh"
        dest: "{{ appl_dir }}/julia-test/environment/runtests.sh"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"

    - name: ""
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/julia/runtests.jl"
        dest: "{{ appl_dir }}/julia-test/julia/runtests.jl"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: ""
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/julia/batch.sh"
        dest: "{{ appl_dir }}/julia-test/julia/batch.sh"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: ""
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/julia/{{ system_name }}.sh"
        dest: "{{ appl_dir }}/julia-test/julia/runtests.sh"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
