- name: "Install julia environment"
  hosts:
    - "group_localhost"
    - "group_lumi"
  become: false

  tasks:
    - name: "Create a directory for julia GPU modulefiles"
      ansible.builtin.file:
        path: "{{ modulefiles_dir }}/julia-amdgpu"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Create a julia GPU module"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/system/{{ system_name }}/julia-amdgpu.lua.j2"
        dest: "{{ modulefiles_dir }}/julia-amdgpu/default.lua"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: "Create a directory for shared depots"
      ansible.builtin.file:
        path: "{{ appl_dir }}/{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "julia-depot"
        - "julia-depot/environments"

    - name: "Copy the global GPU preferences"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/system/{{ system_name }}/amdgpu.toml"
        dest: "{{ appl_dir }}/julia-depot/environments/amdgpu.toml"
        mode: "ug=rw,o=r"
        group: "{{ group }}"
